#!/usr/bin/env bash
# pings an IP address passed as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# if no argument passed

if [ -z "$1" ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

for ((i=1; i<=5; i++)); do
  ping -c 1 "$ip_address"
done

