#!/usr/bin/env bash
#This script displays numbers from 1 to 100 in list format and:
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5
#   Displays "Fizz" when the number is a multiple of 3
#   Displays "Buzz" when the number is a multiple of 5
num="1"
while [ $num -le 100 ]
do
	if [ $((num % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((num % 3)) -eq 0 ]
	then 
		echo "Fizz"
	elif [ $((num % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $num
	fi
	num=$((num + 1))
done
