#!/usr/bin/env bash
#This script displays "Best School" 10 times using while loop.
#On the 9th instance, displays "Hi" then "Best School"

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( i++ ))
done

